### ISSUE TITLE
Update About-Us Page

### ISSUE THREAD

**Issue by BOSS294** [ProtectorGamer/Agro.ai#2]
![image](https://github.com/user-attachments/assets/f698683c-8735-4778-a5ef-e84849645cb7)

Update this as soon as possible 

Update it from here : https://github.com/ProtectorGamer/Agro.ai/blob/main/Assets/Contents/about-us.php

**Comment by ProtectorGamer** [comment]
Thanks for providing the upgrading suggestion.
Required About US for the Website has been updated and fill upto date with the required data set.

https://github.com/ProtectorGamer/Agro.ai/blob/main/Assets/Contents/about-us.php 
has been updated respectively.
